name: RefactoringMiner Diff Action
description: 'GitHub Action to perform diff operations using RefactoringMiner and generate a report of refactorings between two commits or pull requests.'
branding:
  icon: anchor
  color: green

inputs:
  URL:
    description: 'URL of the repository for the diff operation'
    required: true
  OAuthToken:
    description: 'OAuthToken for read the commit/pr information (Only required for private urls)'
    required: false
    default: ${{ github.token }}

  screenshot:
    description: 'Name of the file that you want to take screenshot of'
    required: false
    default: ''

  fromDockerHub:
    description: 'If true then pulls the RefactoringMiner image from DockerHub; if false, builds it from the repo'
    required: false
    default: 'true'
  
outputs:
  artifact_url:
    description: 'URL to download the generated diff artifact'

runs:
  using: 'node20'
  main: 'dist/index.js'